# Generated by Django 4.2 on 2025-12-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stdata',
            name='address',
        ),
        migrations.AddField(
            model_name='stdata',
            name='mobile',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
