# Generated by Django 4.2 on 2025-12-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_remove_stdata_address_stdata_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdata',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
