# Generated by Django 4.2 on 2025-12-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_remove_stdata_address_remove_stdata_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes_cls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.stdata')),
            ],
        ),
    ]
