# Generated by Django 4.2 on 2025-12-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_artist',
            old_name='mobile',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='register_artist',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
