# Generated by Django 4.2 on 2025-11-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersignup',
            name='confirmpassword',
        ),
    ]
