# Generated by Django 4.2 on 2025-11-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_loginform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginform',
            old_name='username',
            new_name='Emailaddress',
        ),
    ]
