# Generated by Django 4.2 on 2025-12-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_contact_us_mynotes_product_userdata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_us',
        ),
        migrations.RemoveField(
            model_name='mynotes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='mynotes',
        ),
    ]
