# Generated by Django 4.2 on 2025-12-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_delete_contact_us_remove_mynotes_user_delete_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='profile_img',
        ),
    ]
